command! RenameTerm lua require'terminals'.terminals:renameTerm()
command! NextTerm lua require'terminals'.terminals:nextTerm()
command! PrevTerm lua require'terminals'.terminals:prevTerm()
command! NewTerm lua require'terminals'.terminals:newTerm() 
command! ToggleZoom lua require'winSizing'.toggleZoom()
command! Terminals lua require'customPicker'.termPick()
command! ShowTerms lua require'terminals'.terminals:show()
command! ToggleTerm lua require'terminals'.terminals:toggle()

autocmd TermClose * lua require'terminals'.terminals:setCurrent()
autocmd BufWinEnter * lua require'terminals'.terminals:setCurrent()
autocmd WinEnter * lua require'terminals'.terminals:setCurrent()
autocmd WinLeave * lua require'terminals'.terminals:setCurrent()
autocmd TermClose * lua require'winSizing'.winInfo()
autocmd WinNew * lua require'winSizing'.winInfo()
